### ISSUE TITLE
Version 2 ideas and discussion

### ISSUE THREAD

**Issue by maticzav** [opencollective/opencollective-bot#8]
Hey everyone 👋,

This issue is intended to serve as the melting pot of the ideas for the next version of `opencollective-bot` which will probably launch as the official OpenCollective bot.

I suggest you first read the proposal for V3 of Open Collective (opencollective/opencollective#1745) before diving in to get an idea of where the platform is heading.

> I will introduce ideas as my own for clearance, though most of them come from discussion with @xdamman and @znarf.

In my opinion, the goal of Open Collective Bot is to inform as many people as possible about your collective and clearly show the benefits of donating to it. Considering that, it makes little sense only to message the thread once it has been closed (the current functionality). Therefore, the goal of the next version is to provide a more engaging experience with the consumers. To better understand the basis of the upcoming release, I have composed a list of benefits that the bot would tackle;

__As a backer:__

* You want to receive priority support with issues opened in the backed projects.

__As a maintainer:__

* You want to visualise why it makes sense to donate to open collective.
* Receive notification or some other indication of a submitted priority issue (`label`).
* Limit priority issues for only certain types of tiers.
* Customise the message displayed to the users.

> Let me know if you have any other suggestions.

## RFC

Create a bot that will message the issue upon its opening. Depending on the status of the issue author (backer/non-backer) the bot will display different messages.

```
# Backer
Hey 👋,
Thank you for opening this issue. Because you are a backer, we will give you priority support. 
We also labelled your issue `priority` so that we don't forget about it.
Thank you for helping us.

# Non-backer

Hey 👋,
Thank you for opening this issue. We noticed that you are not a backer of our collective yet. 
To get maximum support from our team, we suggest you donate to our team.
We will try to get back to you as soon as possible.
```

The bot should also make sure that it removes the priority label from the issues where authors do not back the project.

As suggested in #5, we should consider organisations with multiple members. If one of the organisation members, for example, opens an issue he or she should receive support even though their organisation is backing the project.

(I believe this is best done with the use of OpenCollective members API as Github might have limited access to members of an organisation).

Besides that, we should also provide more flexible customisation options for the displayed message with dynamic collective link insert (`<link>`).

### Config

`API`
```yml
opencollective: https://opencollective.com/graphql-shield
tiers:
  [tiername]:
    label: priority
    message: |
      Hey :wave:,
      This is an optional message to your audience. Check the default message below.
```

`default`

```yml
opencollective: https://opencollective.com/graphql-shield
tiers:
  backers:
    label: priority
    message: |
      Hey :wave:,
      We will take special care of your issue! ...
```

**Comment by ghuntley** [comment]
Ship it ship it ship it. Yes. 🥰🥰🥰🥰

**Comment by Betree** [comment]
Great specs @maticzav! Some ideas:

- Ignore maintainers

Somehow we should also check if the user creating the issue is a maintainer (either from Github API, or from Open Collective member type=ADMIN). As a maintainer, I don't need the bot to post on my own issues ;)

- Templating

Templating could be useful to customize message. For now I can think of the following variables:
    - `assignees`: Issue assignee(s)
    - `owner`: Issue creator

- Advanced filtering

For the message posted when issue is closed, it would be great to have multiple messages and to select one with advanced conditions. For example @jhipster (one of Open Collective's collectives) uses Github labels as a bounty system where people get paid by submitting their expense to Open Collective.

So we can imagine having something like:

```yaml
opencollective: https://opencollective.com/generator-jhipster
issues:
  - member_type: [BACKER, SPONSOR]
    when: opened
    add_label: priority
    message: |
      Hey :wave:,
      This is an optional message to your audience. Check the default message below.
  - when: closed
    has_label: BOUNTY
    message: |
      Hey @{ASSIGNEE}, thanks for completing this issue!
      Claim your bounty now on [Open Collective](https://opencollective.com/generator-jhipster/expenses/new)
```

**Comment by maticzav** [comment]
@Betree I like the idea of having a list of rules instead of an object-like structure. `when`, however, in my opinion, seems like overkill and would better suit another Github App or perhaps a future version of OpenCollective.

Updated config would, therefore, follow the example below.

```yml
opencollective: https://opencollective.com/generator-jhipster
issues:
  - tier: [BACKER, SPONSOR]
     label: priority
     message: |
       Hey :wave:,
       This is an optional message to your audience. Check the default message below.
  - tier: [EXTERNAL]
     label: priority
     message: |
       Hey :wave:,
       Donate!!!
```
---
Besides that, after discussing the organisation flow with @znarf, I believe it would make more sense to use Github's user organisation API (`https://api.github.com/users/maticzav/orgs`, for example) and check whether any of them is backing the project.
